
name: Generate Files

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Execute generate script
      run: |
        cd .github/scripts
        python generate-files.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add files/
        if git diff --staged --quiet; then
          echo "No changes in files/"
        else
          git commit -m "Auto-regenerate files/ directory"
          git push
        fi
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './files'  # Despliega solo la carpeta files/
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4